export const SET_PRICE = 'SET_PRICE'

export const ADD_PROMOCODE = 'ADD_PROMOCODE'
export const SET_PROMOCODE = 'SET_PROMOCODE'

export const ADD_RESERVATION = 'ADD_RESERVATION'
export const SET_RESERVATION_LIST = 'SET_RESERVATION_LIST'
